version: '2'
services:
    smurfhouse-app:
        image: smurfhouse
        external_links:
            - smurfhouse-postgresql:postgresql
            - smurfhouse-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/smurfHouse
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    smurfhouse-postgresql:
        extends:
            file: postgresql.yml
            service: smurfhouse-postgresql
    smurfhouse-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: smurfhouse-elasticsearch
